### ISSUE TITLE
ssh_login 

### ISSUE THREAD

**Issue by squid22** [lanjelot/patator#134]
I noticed that when the password file includes passwords such as:
wh0xf15
f0xf1re

The application crashes with the following message:

```
Process Producer:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/patator", line 1700, in produce
    for _ in f:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte

```

**Comment by squid22** [comment]
I just cloned the project after your commit... tried again and got the same exact error. 

```
02:06:36 patator    INFO - Starting Patator v0.7 (https://github.com/lanjelot/patator) at 2020-05-07 02:06 EDT
Process Producer:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/patator", line 1700, in produce
    for _ in f:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte

```

**Comment by lanjelot** [comment]
if you had cloned the project it would have said `Patator v0.8-dev`
