### ISSUE TITLE
Some bug while `multiprocessing` module working.

### ISSUE THREAD

**Issue by SingularBunny** [lanjelot/patator#18]
I'm try to run `patator` with `ssh_login host=NET1 user=COMBO00 password=COMBO01 1=so.many.nets.with/mask 0=/root/Desktop/patator-master/wordList_ssh.txt -x free=host:code=0 -x ignore:mesg="Authentication failed." -x free=host:fgrep="Unable to connect to" -l /root/Desktop/patator-master/logs --max-retries=0 -t 10 --allow-ignore-failures -x ignore:fgrep="paramiko.ssh_exception.SSHException" -d` parameters.
OS: Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux
Throws an exception:

```
Process LogSvc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 761, in process_logs
    pname, action, args = pipe.recv()
UnpicklingError: invalid load key, '7'.
Process Consumer-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
Process Consumer-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1805, in consume
    self.register_free(payload, actions['free'])
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1482, in register_free
    logger.debug('free_list updated: %s' % self.ns.free_list)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
    self.send('debug', msg)
Process Consumer-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
Process Consumer-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1805, in consume
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
    self.register_free(payload, actions['free'])
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1482, in register_free
    logger.debug('free_list updated: %s' % self.ns.free_list)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1779, in consume
    logger.debug('caught: %s' % mesg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1779, in consume
    logger.debug('caught: %s' % mesg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1779, in consume
    logger.debug('caught: %s' % mesg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/root/pycharm-community-4.5.3/helpers/pydev/pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/pycharm-community-4.5.3/helpers/pydev/pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/PycharmProjects/SSHBrute/j4lpmod.py", line 644, in <module>
    powder.fire()
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1504, in fire
    logger.debug('active: %s' % active)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1779, in consume
    logger.debug('caught: %s' % mesg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
```

**Comment by SingularBunny** [comment]
And yet...with same parameters...
```
Process LogSvc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 761, in process_logs
    pname, action, args = pipe.recv()
EOFError
Process Consumer-7:
Process Consumer-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
Process Consumer-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
Process Consumer-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
Process Consumer-0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
Process Consumer-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
IOError: [Errno 32] Broken pipe
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
IOError: [Errno 32] Broken pipe
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1779, in consume
    logger.debug('caught: %s' % mesg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/root/PycharmProjects/SSHBrute/j4lpmod.py", line 644, in <module>
    powder.fire()
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1504, in fire
    logger.debug('active: %s' % active)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 663, in debug
    self.send('debug', msg)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
```

**Comment by SingularBunny** [comment]
Issue reproduces with a big num of threads.

**Comment by SingularBunny** [comment]
I'm find solution of this problem!
From Python documentation:
>Note that data in a pipe may become corrupted if two processes (or threads) try to read from or >write to the same end of the pipe at the same time.
Of course, it happens that multiple consumer processes do logging at same time.
Solution is to use `Queue` instead of `Pipe`.
In `__init__` method of `Controller` should replace:
-`pipe = multiprocessing.Pipe(duplex=False)`
+`pipe = manager.Pipe()`
In `send` method of `Logger` class:
-`self.pipe.send((self.name, action, args))`
+`self.pipe.put((self.name, action, args))`
In method `process_logs` (while True cycle):
-`pname, action, args = pipe.recv()`
+`pname, action, args = pipe.get()`
Pretty works for a few hours.

**Comment by lanjelot** [comment]
Thanks for the fix @SingularBunny! Can you test and let me know if you can still reproduce this issue?
