### ISSUE TITLE
issue with encoding

### ISSUE THREAD

**Issue by d7x** [lanjelot/patator#182]
The following block causes potential issues with encoding in python3: 
```   
    915 PY3 = sys.version_info >= (3,)
    916 if PY3: # http://python3porting.com/problems.html
    917   def b(x):
    918     return x.encode('ISO-8859-1')
    919   def B(x):
    920     return x.decode('latin-1')
```
The error returned by the original code is caused by the call to .decode on line 920 :
``` Traceback (most recent call last):
  File "/usr/bin/patator", line 3640, in debug_func
    s = B(s)
  File "/usr/bin/patator", line 921, in B
    return x.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 37: invalid continuation byte
/usr/bin/patator:3698: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
Traceback (most recent call last):
  File "/usr/bin/patator", line 3640, in debug_func
    s = B(s)
  File "/usr/bin/patator", line 921, in B
    return x.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 37: invalid continuation byte
```

This could be fixed by replacing the call to .decode with x.decode('latin-1') for example, or any other encoding different from UTF-8.

**Comment by lanjelot** [comment]
The code you quoted is not from the latest version.
Please provide a command line to reproduce with latest version.
