### ISSUE TITLE
RANGE letters with numbers and special characters

### ISSUE THREAD

**Issue by rafis** [lanjelot/patator#19]
Range letters support only letters, it it possible to support for any ASCII character code?

```
password=RANGE0 0=letters:0000-zzzzzz

Process Producer:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./patator.py", line 1607, in produce
    it = RangeIter(typ, opt)
  File "./patator.py", line 1085, in __init__
    self.size = count(last) - count(first) + 1
  File "./patator.py", line 1078, in count
    z = charset.index(c) + 1
ValueError: '0' is not in list
```

**Comment by lanjelot** [comment]
try `password=_@_RANGE0_@_ 0=hex:0x00-0xffff -e _@_:unhex`
