### ISSUE TITLE
Timeout rising bug

### ISSUE THREAD

**Issue by SingularBunny** [lanjelot/patator#23]
If timeout expires while executed `except` block of `consume` method, consumer  process crashed.

```
Process Consumer-76:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1788, in consume
    sleep(try_count * .1)
  File "/root/PycharmProjects/SSHBrute/patator.py", line 1132, in raise_timeout
    raise TimeoutError('timed out')
TimeoutError: timed out
```

**Comment by SingularBunny** [comment]
In `finally` block of the same try-except-finally construction this exception throws too.

**Comment by lanjelot** [comment]
thx for reporting m8, can you submit a patch that fixes this issue?

**Comment by SingularBunny** [comment]
I'm fix it like this, but it very not professional, because it replicate piece of code)):
```
                    except:
                        try:
                            mesg = '%s %s' % sys.exc_info()[:2]
                            logger.debug('caught: %s' % mesg)

                            # logging.exception(sys.exc_info()[1])

                            resp = self.module.Response('xxx', mesg, timing=time() - start_time)

                            if hasattr(module, 'reset'):
                                module.reset()

                            sleep(try_count * .1)
                            continue
                        except:
                            mesg = '%s %s' % sys.exc_info()[:2]
                            logger.debug('caught: %s' % mesg)

                            # logging.exception(sys.exc_info()[1])

                            resp = self.module.Response('xxx', mesg, timing=time() - start_time)

                            if hasattr(module, 'reset'):
                                module.reset()

                            sleep(try_count * .1)
                            continue

                    finally:
                        try:
                            disable_alarm()
                        except:
                            pass
```

**Comment by SingularBunny** [comment]
Sebastien, i think, you should write your own timeout thread safe manager without os built-ins.  It should provide multi os support.
