### ISSUE TITLE
Patator break with  updated pip

### ISSUE THREAD

**Issue by Securityinfos** [lanjelot/patator#25]
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "patator.py", line 761, in process_logs
    pname, action, args = pipe.recv()
EOFError
Process Consumer-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "patator.py", line 663, in debug
    self.send('debug', msg)
  File "patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "patator.py", line 663, in debug
    self.send('debug', msg)
  File "patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Consumer-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "patator.py", line 1745, in consume
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "patator.py", line 663, in debug
    self.send('debug', msg)
  File "patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
    logger.debug('product: %s' % prod)
  File "patator.py", line 663, in debug
    self.send('debug', msg)
  File "patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "patator.py", line 663, in debug
    self.send('debug', msg)
  File "patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Process Consumer-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "patator.py", line 1745, in consume
    logger.debug('product: %s' % prod)
  File "patator.py", line 663, in debug
    self.send('debug', msg)
  File "patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
ERROR:root:[Errno 32] Broken pipe
Traceback (most recent call last):
  File "patator.py", line 1489, in fire
    self.monitor_progress()
  File "patator.py", line 1819, in monitor_progress
    self.report_progress()
  File "patator.py", line 1851, in report_progress
    logger.result('fail', resp, current, offset)
  File "patator.py", line 648, in result
    self.send('result', *args)
  File "patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "patator.py", line 4453, in <module>
    powder.fire()
  File "patator.py", line 1501, in fire
    self.report_progress()
  File "patator.py", line 1851, in report_progress
    logger.result('fail', resp, current, offset)
  File "patator.py", line 648, in result
    self.send('result', *args)
  File "patator.py", line 639, in send
    self.pipe.send((self.name, action, args))
IOError: [Errno 32] Broken pipe

**Comment by lanjelot** [comment]
That's a poorly written bug report. Please provide more information. Command line, environment, lib versions, etc.

**Comment by SingularBunny** [comment]
Hi Sebastien! There is duplication of my issue (https://github.com/lanjelot/patator/issues/25). Solution provided in comments.

**Comment by lanjelot** [comment]
Closing this as issue #18 is now closed.
