### ISSUE TITLE
Problem with pop_login module

### ISSUE THREAD

**Issue by dkorzhevin** [lanjelot/patator#26]
Hi

I meet next problem with patator in Kali 2.0. patator version 0.5-0kali1

```
# proxychains patator pop_login host=172.16.0.10 user=petrov.v.a@company.lab password=FILE0 0=/usr/share/ncrack/default.pwd -x ignore:code=-ERR
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-response|: kali does not exist
09:21:43 patator    INFO - Starting Patator v0.5 (http://code.google.com/p/patator/) at 2015-09-24 09:21 EEST
09:21:43 patator    INFO - 
09:21:43 patator    INFO - code  size | candidate                          |   num | mesg
09:21:43 patator    INFO - ----------------------------------------------------------------------
|S-chain|-<>-127.0.0.1:9050-<><>-172.16.0.10:110-|S-chain|-<>-127.0.0.1:9050-<><>-172.16.0.10:110-|S-chain|-<>-127.0.0.1:9050-<><>-172.16.0.10:110-|S-chain|-<>-127.0.0.1:9050-<><>-172.16.0.10:110-|S-chain|-<>-12
7.0.0.1:9050-<><>-172.16.0.10:110-|S-chain|-<>-127.0.0.1:9050-<><>-172.16.0.10:110-|S-chain|-<>-127.0.0.1:9050-<><>-172.16.0.10:110-|S-chain|-<>-127.0.0.1:9050-<><>-172.16.0.10:110-|S-chain|-<>-127.0.0.1:9050-<>
<>-172.16.0.10:110-|S-chain|-<>-127.0.0.1:9050-<><>-172.16.0.10:110-<><>-OK
<><>-OK
<><>-OK
<><>-OK
<><>-OK
<><>-OK
<><>-OK
<><>-OK
<><>-OK
<><>-OK
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/patator", line 1450, in consume
    module.reset()
  File "/usr/bin/patator", line 1743, in reset
    c.close()
  File "/usr/bin/patator", line 2351, in close
    self.fp.quit()
  File "/usr/lib/python2.7/poplib.py", line 259, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/usr/lib/python2.7/poplib.py", line 132, in _getresp
    resp, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 112, in _getline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

09:24:11 patator    INFO - Hits/Done/Skip/Fail/Size: 0/190/0/0/5083, Avg: 1 r/s, Time: 0h 2m 27s
Exception socket.timeout: timeout('timed out',) in <bound method POP_login.__del__ of <__main__.POP_login instance at 0x7fc5d95b1050>> ignored
```

**Comment by SingularBunny** [comment]
Hi, Dmitry! There is a duplication of https://github.com/lanjelot/patator/issues/23 issue. Try suggestion from comments.

**Comment by lanjelot** [comment]
closing as patator version 0.5-0kali1 is not the latest version.
