### ISSUE TITLE
PicklingError: Can't pickle <function <lambda>

### ISSUE THREAD

**Issue by SingularBunny** [lanjelot/patator#5]
OS Windows 7, Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)],
Patator was started with next params: ftp_login host=NET0 user=anonymous password=test@example.com 0=192.168.0.1/250

And give that:
```
C:\Python27\python.exe C:/Users/StupidUser/PycharmProjects/Tup/patator.py ftp_login host=NET0 user=anonymous password=test@example.com 0=192.168.0.1/250
Traceback (most recent call last):
  File "C:/Users/DD/PycharmProjects/Tup/patator.py", line 638, in <module>
    manager.start(lambda: signal.signal(signal.SIGINT, signal.SIG_IGN))
  File "C:\Python27\lib\multiprocessing\managers.py", line 524, in start
    self._process.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 562, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <function <lambda> at 0x01CD3270>: it's not found as __main__.<lambda>

Process finished with exit code 1
```
Its known bug with trying to pickle lambda.

Bug in the 638 line:
`manager.start(lambda: signal.signal(signal.SIGINT, signal.SIG_IGN))`
But i can't understand... Is `manager.start(lambda: signal.signal(signal.SIGINT, signal.SIG_IGN))` not equal `manager.start(signal.signal(signal.SIGINT, signal.SIG_IGN))`?? Is it useful hack?))

**Comment by SingularBunny** [comment]
Resolved
