### ISSUE TITLE
RuntimeError (Compat branch)

### ISSUE THREAD

**Issue by SingularBunny** [lanjelot/patator#8]
OS Windows 7, Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)],
i'm tested 'compat' branch. Problem with lambda function is resolved, but some exception throws:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 495, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Users\DD\PycharmProjects\Patator\patator.py", line 645, in <module>
    manager.start()
  File "C:\Python27\lib\multiprocessing\managers.py", line 524, in start
    self._process.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
Traceback (most recent call last):
  File "C:/Users/DD/PycharmProjects/Patator/patator.py", line 645, in <module>
    manager.start()
  File "C:\Python27\lib\multiprocessing\managers.py", line 528, in start
    self._address = reader.recv()
EOFError
```

I can't understand yet why it occurs. Using `freeze_support()` in main thread doesn't resolve this poblem.

**Comment by lanjelot** [comment]
yep i could reproduce your issue. I've been working on adding Windows support, and i should be able to push soon. Cheers

**Comment by SingularBunny** [comment]
Thanks for work!

**Comment by lanjelot** [comment]
hey mate can you test again with the latest version of the master branch? it should work now, let me know

**Comment by SingularBunny** [comment]
Hi Sebastien! Work great! I close this issue. One question... Why you don't merge compat and master branches?

**Comment by lanjelot** [comment]
thx mate. I've actually merged the code from compat into master without actually doing a git merge. But i will delete the compat branch now
