### ISSUE TITLE
Filter Error "-x free=host:code=200"

### ISSUE THREAD

**Issue by nemonnet** [lanjelot/patator#81]
I try to enable the function to skip the host with the password already found:
`./patator.py http_fuzz url="FILE2/Login.cgi" -l ./data/ method=GET user_pass=FILE0:FILE1 0=login.txt 1=pwd.txt 2=target.txt timeout_tcp=3 -x free=host:code=200`
I see errors in the console:
20:31:37 patator    INFO - Starting Patator v0.7-beta (https://github.com/lanjelot/patator) at 2017-12-10 20:31 +10
20:31:37 patator    INFO -                                                                              
20:31:37 patator    INFO - code size:clen       time | candidate                          |   num | mesg
20:31:37 patator    INFO - -----------------------------------------------------------------------------
Process Consumer-0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./patator.py", line 1884, in consume
    self.register_free(payload, actions['free'])
  File "./patator.py", line 1549, in register_free
    self.ns.free_list += [','.join('%s=%s' % (k, payload[k]) for k in opts.split('+'))]
  File "./patator.py", line 1549, in <genexpr>
    self.ns.free_list += [','.join('%s=%s' % (k, payload[k]) for k in opts.split('+'))]
KeyError: 'host'
20:31:38 patator    INFO - 200  482:265        0.927 | admin:1234:*.*.*.*:1234    |     1 | HTTP/1.0 200 OK
Process Consumer-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./patator.py", line 1884, in consume
    self.register_free(payload, actions['free'])
  File "./patator.py", line 1549, in register_free
    self.ns.free_list += [','.join('%s=%s' % (k, payload[k]) for k in opts.split('+'))]
  File "./patator.py", line 1549, in <genexpr>
    self.ns.free_list += [','.join('%s=%s' % (k, payload[k]) for k in opts.split('+'))]
KeyError: 'host'
Process Consumer-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./patator.py", line 1884, in consume
    self.register_free(payload, actions['free'])
  File "./patator.py", line 1549, in register_free
    self.ns.free_list += [','.join('%s=%s' % (k, payload[k]) for k in opts.split('+'))]
  File "./patator.py", line 1549, in <genexpr>
    self.ns.free_list += [','.join('%s=%s' % (k, payload[k]) for k in opts.split('+'))]
KeyError: 'host'
20:31:39 patator    INFO - 200  482:265        0.951 | admin:4321:*.*.*.*:1234    |     2 | HTTP/1.0 200 OK
20:31:39 patator    INFO - 200  482:265        1.013 | admin:12345:*.*.*.*:1234   |     3 | HTTP/1.0 200 OK
`
If you put another code, for example code = 0, then there is no error.

**Comment by lanjelot** [comment]
you need to use /patator.py http_fuzz host=FILE2 path=/Login.cgi
