### ISSUE TITLE
Some bug arising from features of the windows command line

### ISSUE THREAD

**Issue by SingularBunny** [lanjelot/patator#9]
OS Windows 7, Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)],
Patator v 0.6, but in new patator issue was reproduced, Exception throws:
```
C:\Python27\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 4.0.3\helpers\pydev\pydevd.py" --multiproc --client 127.0.0.1 --port 52935 --file C:/Users/DD/PycharmProjects/Nagibator/patator.py http_fuzz url=http://10.0.0.1/phpmyadmin/index.php method=POST follow=1 accept_cookie=1 body='pma_username=root&pma_password=FILE0&server=1&lang=en' 0=passwords.txt -x ignore:fgrep='Cannot log in to the MySQL server'
pydev debugger: process 4416 is connecting

Connected to pydev debugger (build 139.1001)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 4.0.3\helpers\pydev\pydevd.py", line 2222, in <module>
    globals = debugger.run(setup['file'], None, None)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 4.0.3\helpers\pydev\pydevd.py", line 1648, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/DD/PycharmProjects/Nagibator/patator.py", line 4097, in <module>
    powder = ctrl(module, [name] + argv[1:])
  File "C:/Users/DD/PycharmProjects/Nagibator/patator.py", line 1186, in __init__
    for k, v in self.expand_key(arg):
ValueError: need more than 1 value to unpack
```

I run pataror under debugger and found some interesting feature:
```
argv = ['http_fuzz', 'url=http://10.0.0.1/phpmyadmin/index.php', 'method=POST', 'follow=1', 'accept_cookie=1', "body='pma_username=root&pma_password=FILE0&server=1&lang=en'", '0=passwords.txt', '-x', "ignore:fgrep='Cannot", 'log', 'in', 'to', 'the', 'MySQL', "server'"] 
```
**Windows console doesn't understand that `ignore:fgrep='Cannot log in to the MySQL server'` is a single element.**
But problem may be solved if instad of ' using ": `ignore:fgrep="Cannot log in to the MySQL server"`

Should i close issue, or it will be fixed for compatibility?

**Comment by lanjelot** [comment]
properly quoting arguments on the command line has got nothing to do with patator :)

**Comment by SingularBunny** [comment]
Ok, but I got example from the readme, and throws exception. Formally it is compatibility bug, but if see trough"notforscriptkiddy" philosophy of patator, of course, it's my foult.))
