### ISSUE TITLE
Error in kali linux and the one i also clone from Github.

### ISSUE THREAD

**Issue by filebe777** [lanjelot/patator#92]
patator
Traceback (most recent call last):
  File "/usr/bin/patator", line 3765, in <module>
    from pysnmp.entity.rfc3413.oneliner import cmdgen
  File "/usr/lib/python2.7/dist-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 10, in <module>
    from pysnmp.hlapi.asyncore import *
  File "/usr/lib/python2.7/dist-packages/pysnmp/hlapi/__init__.py", line 7, in <module>
    from pysnmp.proto.rfc1902 import *
  File "/usr/lib/python2.7/dist-packages/pysnmp/proto/rfc1902.py", line 9, in <module>
    from pysnmp.proto import rfc1155, error
  File "/usr/lib/python2.7/dist-packages/pysnmp/proto/rfc1155.py", line 50, in <module>
    class NetworkAddress(univ.Choice):
  File "/usr/lib/python2.7/dist-packages/pysnmp/proto/rfc1155.py", line 55, in NetworkAddress
    def clone(self, value=univ.noValue, **kwargs):
AttributeError: 'module' object has no attribute 'noValue'

How do i fix this please?

**Comment by gabontau** [comment]
pip install pysnmp==4.2.4
